### ISSUE TITLE
[Feature request] Rule builder script

### ISSUE THREAD

**Issue by GamingGuy003** [Raspirus/yara-rules#3]
## Description

It would be useful to have a script / bulder action that fetches the newest rules and creates a release, as to not have to do it manually. Possibly automate this to run like once a month?

## Requirements 

A python script would most likely do the trick or a Github action

**Comment by Benji377** [comment]
I feel like this is related to #1 ?

**Comment by Benji377** [comment]
@GamingGuy003 I have now created a GitHub Action that does the following:
1. Calculates the version and tag name like this: v{year_number}.{month_number}.0
    1.1.  This creates something like this: for January 2025 → v25.01.0
    1.2. The last number (0) can be used for manual revisions or updates in between months
2. Creates a `tar.gz` archive that includes all rules and the windows script, preserving the folder structure
3. Creates a GitHub release with the version and name discussed above.

**Additional notes:**
- The GitHub Action runs at 03:00 (AM) on the first day of each month (That's why the version schema makes sense in my opinion)
- GitHub automatically adds the source code as zip and tar to each release, so Raspirus needs to be adapted to ignore those and only use the generated `tar.gz` bundle
- The action currently creates draft releases and need to be published manually by someone. This can be changed easily, by updating the boolean in the last step of the pipeline:
  ```yml
        - name: Create GitHub release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ steps.version.outputs.tag_name }}
            name: ${{ steps.version.outputs.tag_name }}
            draft: true # Change this to false!
            generate_release_notes: true
            files: ${{ steps.version.outputs.file_name }}.tar.gz
  ```
- You can manually run the GitHub Action, to test it. Keep in mind that if you set `draft: false` it will immediately publish it! I might change this later to be true when run manually.

**Comment by Benji377** [comment]
To make the Action publish a release when the cron job runs and create a draft one when run manually, here is how the code needs to be updated. Once approved, I can just add it:

```yml
      - name: Determine if release should be a draft
        id: draft
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "is_draft=true" >> $GITHUB_OUTPUT
          else
            echo "is_draft=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          name: ${{ steps.version.outputs.tag_name }}
          draft: ${{ steps.draft.outputs.is_draft }}
          generate_release_notes: true
          files: ${{ steps.version.outputs.file_name }}.tar.gz
```
